spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.101:3306/stumybatisplus?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    com.zx.mp.dao: trace

mybatis-plus:
  type-aliases-package: com.zx.mp.entity
  mapper-locations: classpath*:/mapper/**/*.xml
